<?php

return (new PhpCsFixer\Config())
    ->setRules([
        '@PSR12' => true,
        'array_syntax' => ['syntax' => 'short'],
        'ordered_imports' => ['sortAlgorithm' => 'alpha'],
        'no_unused_imports' => true,
        'simplified_if_return' => true,
        'no_useless_else' => true,
        'no_unneeded_curly_braces' => true,
        'no_superfluous_elseif' => true,
        'elseif' => true,
        'no_trailing_comma_in_singleline_array' => true,
        'no_whitespace_before_comma_in_array' => true,
        'trim_array_spaces' => true,
        'whitespace_after_comma_in_array' => true,
        'magic_constant_casing' => true,
        'magic_method_casing' => true,
        'native_function_casing' => true,
        'cast_spaces' => true,
        'no_short_bool_cast' => true,
        'no_unset_cast' => true,
        'short_scalar_cast' => true,
        'fully_qualified_strict_types' => true,
        'combine_consecutive_issets' => true,
        'combine_consecutive_unsets' => true,
        'list_syntax' => ['syntax' => 'short'],
        'clean_namespace' => true,
        'no_blank_lines_before_namespace' => true,
        'no_leading_namespace_whitespace' => true,
        'concat_space' => ['spacing' => 'one'],
        'increment_style' => 'post',
        'not_operator_with_space' => true,
        'object_operator_without_whitespace' => true,
        'standardize_not_equals' => true,
        'ternary_to_null_coalescing' => true,
        'unary_operator_spaces' => true,
        'no_useless_return' => true,
        'return_assignment' => true,
        'simplified_null_return' => true,
        'no_singleline_whitespace_before_semicolons' => true,
        'single_quote' => true,
        'array_indentation' => true,
        'blank_line_before_statement' => [
            'break',
            'continue',
            'declare',
            'exit',
            'for',
            'foreach',
            'goto',
            'if',
            'include',
            'include_once',
            'require',
            'require_once',
            'return',
            'switch',
            'throw',
            'try',
            'while',
            'yield',
            'yield_from',
        ],
        'method_chaining_indentation' => true,
    ])
    ->setLineEnding("\n");

